//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UDLAPSIFEntities : DbContext
    {
        public UDLAPSIFEntities()
            : base("name=UDLAPSIFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PTONOM_CAT_COSTCENTER> PTONOM_CAT_COSTCENTER { get; set; }
        public DbSet<PTONOM_CAT_CUENTAS> PTONOM_CAT_CUENTAS { get; set; }
        public DbSet<PTONOM_CAT_LEDGERACCOUNT> PTONOM_CAT_LEDGERACCOUNT { get; set; }
        public DbSet<PTONOM_CAT_SPENDCATEGORY> PTONOM_CAT_SPENDCATEGORY { get; set; }
        public DbSet<PTONOM_CAT_PROJECT> PTONOM_CAT_PROJECT { get; set; }
        public DbSet<PTONOM_CAT_CURRENCY> PTONOM_CAT_CURRENCY { get; set; }
        public DbSet<PTONOM_CAT_PARAMETERS> PTONOM_CAT_PARAMETERS { get; set; }
        public DbSet<xNOMExcelRH> xNOMExcelRH { get; set; }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_COSTCENTER_AGREGA_ACTUALIZA_Result> UDLAPSIF_PTONOM_COSTCENTER_AGREGA_ACTUALIZA(Nullable<int> iD_CC, string cC, string dESCRIPCION, string nAMEUPDATE, Nullable<bool> eSTATUS, string iDUSER)
        {
            var iD_CCParameter = iD_CC.HasValue ?
                new ObjectParameter("ID_CC", iD_CC) :
                new ObjectParameter("ID_CC", typeof(int));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var nAMEUPDATEParameter = nAMEUPDATE != null ?
                new ObjectParameter("NAMEUPDATE", nAMEUPDATE) :
                new ObjectParameter("NAMEUPDATE", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_COSTCENTER_AGREGA_ACTUALIZA_Result>("UDLAPSIF_PTONOM_COSTCENTER_AGREGA_ACTUALIZA", iD_CCParameter, cCParameter, dESCRIPCIONParameter, nAMEUPDATEParameter, eSTATUSParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_COSTCENTER_BUSCARCC_Result> UDLAPSIF_PTONOM_COSTCENTER_BUSCARCC(Nullable<int> iD_CC, string cC, string dESCRIPCION, Nullable<bool> eSTATUS)
        {
            var iD_CCParameter = iD_CC.HasValue ?
                new ObjectParameter("ID_CC", iD_CC) :
                new ObjectParameter("ID_CC", typeof(int));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_COSTCENTER_BUSCARCC_Result>("UDLAPSIF_PTONOM_COSTCENTER_BUSCARCC", iD_CCParameter, cCParameter, dESCRIPCIONParameter, eSTATUSParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_COSTCENTER_OBTENCC_Result> UDLAPSIF_PTONOM_COSTCENTER_OBTENCC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_COSTCENTER_OBTENCC_Result>("UDLAPSIF_PTONOM_COSTCENTER_OBTENCC");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_CURRENCY_OBTENCURRENCY_Result> UDLAPSIF_PTONOM_CURRENCY_OBTENCURRENCY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_CURRENCY_OBTENCURRENCY_Result>("UDLAPSIF_PTONOM_CURRENCY_OBTENCURRENCY");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_LEDGERACCOUNT_AGREGA_ACTUALIZA_Result> UDLAPSIF_PTONOM_LEDGERACCOUNT_AGREGA_ACTUALIZA(Nullable<int> iD_LA, string lA, string dESCRIPCION, string nAMEUPDATE, Nullable<bool> eSTATUS, string iDUSER)
        {
            var iD_LAParameter = iD_LA.HasValue ?
                new ObjectParameter("ID_LA", iD_LA) :
                new ObjectParameter("ID_LA", typeof(int));
    
            var lAParameter = lA != null ?
                new ObjectParameter("LA", lA) :
                new ObjectParameter("LA", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var nAMEUPDATEParameter = nAMEUPDATE != null ?
                new ObjectParameter("NAMEUPDATE", nAMEUPDATE) :
                new ObjectParameter("NAMEUPDATE", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_LEDGERACCOUNT_AGREGA_ACTUALIZA_Result>("UDLAPSIF_PTONOM_LEDGERACCOUNT_AGREGA_ACTUALIZA", iD_LAParameter, lAParameter, dESCRIPCIONParameter, nAMEUPDATEParameter, eSTATUSParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_LEDGERACCOUNT_BUSCARLA_Result> UDLAPSIF_PTONOM_LEDGERACCOUNT_BUSCARLA(Nullable<int> iD_LA, string lA, string dESCRIPCION, Nullable<bool> eSTATUS)
        {
            var iD_LAParameter = iD_LA.HasValue ?
                new ObjectParameter("ID_LA", iD_LA) :
                new ObjectParameter("ID_LA", typeof(int));
    
            var lAParameter = lA != null ?
                new ObjectParameter("LA", lA) :
                new ObjectParameter("LA", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_LEDGERACCOUNT_BUSCARLA_Result>("UDLAPSIF_PTONOM_LEDGERACCOUNT_BUSCARLA", iD_LAParameter, lAParameter, dESCRIPCIONParameter, eSTATUSParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_LEDGERACCOUNT_OBTENLA_Result> UDLAPSIF_PTONOM_LEDGERACCOUNT_OBTENLA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_LEDGERACCOUNT_OBTENLA_Result>("UDLAPSIF_PTONOM_LEDGERACCOUNT_OBTENLA");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_ROLES_OBTENROL_Result> UDLAPSIF_PTONOM_ROLES_OBTENROL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_ROLES_OBTENROL_Result>("UDLAPSIF_PTONOM_ROLES_OBTENROL");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_SPENDCATEGORY_AGREGA_ACTUALIZA_Result> UDLAPSIF_PTONOM_SPENDCATEGORY_AGREGA_ACTUALIZA(Nullable<int> iD_SC, string sC, string dESCRIPCION, string nAMEUPDATE, Nullable<bool> eSTATUS, string iDUSER)
        {
            var iD_SCParameter = iD_SC.HasValue ?
                new ObjectParameter("ID_SC", iD_SC) :
                new ObjectParameter("ID_SC", typeof(int));
    
            var sCParameter = sC != null ?
                new ObjectParameter("SC", sC) :
                new ObjectParameter("SC", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var nAMEUPDATEParameter = nAMEUPDATE != null ?
                new ObjectParameter("NAMEUPDATE", nAMEUPDATE) :
                new ObjectParameter("NAMEUPDATE", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_SPENDCATEGORY_AGREGA_ACTUALIZA_Result>("UDLAPSIF_PTONOM_SPENDCATEGORY_AGREGA_ACTUALIZA", iD_SCParameter, sCParameter, dESCRIPCIONParameter, nAMEUPDATEParameter, eSTATUSParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_SPENDCATEGORY_BUSCARSC_Result> UDLAPSIF_PTONOM_SPENDCATEGORY_BUSCARSC(Nullable<int> iD_SC, string sC, string dESCRIPCION, Nullable<bool> eSTATUS)
        {
            var iD_SCParameter = iD_SC.HasValue ?
                new ObjectParameter("ID_SC", iD_SC) :
                new ObjectParameter("ID_SC", typeof(int));
    
            var sCParameter = sC != null ?
                new ObjectParameter("SC", sC) :
                new ObjectParameter("SC", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_SPENDCATEGORY_BUSCARSC_Result>("UDLAPSIF_PTONOM_SPENDCATEGORY_BUSCARSC", iD_SCParameter, sCParameter, dESCRIPCIONParameter, eSTATUSParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_SPENDCATEGORY_OBTENSC_Result> UDLAPSIF_PTONOM_SPENDCATEGORY_OBTENSC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_SPENDCATEGORY_OBTENSC_Result>("UDLAPSIF_PTONOM_SPENDCATEGORY_OBTENSC");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_TIPOCUENTA_OBTENTC_Result> UDLAPSIF_PTONOM_TIPOCUENTA_OBTENTC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_TIPOCUENTA_OBTENTC_Result>("UDLAPSIF_PTONOM_TIPOCUENTA_OBTENTC");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_USUARIOS_AGREGA_ACTUALIZA_Result> UDLAPSIF_PTONOM_USUARIOS_AGREGA_ACTUALIZA(string iDEMPLEADO, string nOMBRE, string eMAIL, Nullable<short> iDROL, Nullable<bool> eSTATUS, string nAMEUPDATE, string iDUSER)
        {
            var iDEMPLEADOParameter = iDEMPLEADO != null ?
                new ObjectParameter("IDEMPLEADO", iDEMPLEADO) :
                new ObjectParameter("IDEMPLEADO", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iDROLParameter = iDROL.HasValue ?
                new ObjectParameter("IDROL", iDROL) :
                new ObjectParameter("IDROL", typeof(short));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var nAMEUPDATEParameter = nAMEUPDATE != null ?
                new ObjectParameter("NAMEUPDATE", nAMEUPDATE) :
                new ObjectParameter("NAMEUPDATE", typeof(string));
    
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_USUARIOS_AGREGA_ACTUALIZA_Result>("UDLAPSIF_PTONOM_USUARIOS_AGREGA_ACTUALIZA", iDEMPLEADOParameter, nOMBREParameter, eMAILParameter, iDROLParameter, eSTATUSParameter, nAMEUPDATEParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_USUARIOS_BUSCARU_Result> UDLAPSIF_PTONOM_USUARIOS_BUSCARU(string iDEMPLEADO, string nOMBRE, Nullable<short> iDROL, Nullable<bool> eSTATUS)
        {
            var iDEMPLEADOParameter = iDEMPLEADO != null ?
                new ObjectParameter("IDEMPLEADO", iDEMPLEADO) :
                new ObjectParameter("IDEMPLEADO", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var iDROLParameter = iDROL.HasValue ?
                new ObjectParameter("IDROL", iDROL) :
                new ObjectParameter("IDROL", typeof(short));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_USUARIOS_BUSCARU_Result>("UDLAPSIF_PTONOM_USUARIOS_BUSCARU", iDEMPLEADOParameter, nOMBREParameter, iDROLParameter, eSTATUSParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_VALIDAACCESO_Result> UDLAPSIF_PTONOM_VALIDAACCESO(string eMPLEADO)
        {
            var eMPLEADOParameter = eMPLEADO != null ?
                new ObjectParameter("EMPLEADO", eMPLEADO) :
                new ObjectParameter("EMPLEADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_VALIDAACCESO_Result>("UDLAPSIF_PTONOM_VALIDAACCESO", eMPLEADOParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_PARAMETERS_AGREGA_ACTUALIZA_Result> UDLAPSIF_PTONOM_PARAMETERS_AGREGA_ACTUALIZA(Nullable<short> iDPARAM, string dESCRIBEPARAM, string vALUEPARAM, Nullable<bool> eSTATUS, string nAMEUPDATE, string iDUSER)
        {
            var iDPARAMParameter = iDPARAM.HasValue ?
                new ObjectParameter("IDPARAM", iDPARAM) :
                new ObjectParameter("IDPARAM", typeof(short));
    
            var dESCRIBEPARAMParameter = dESCRIBEPARAM != null ?
                new ObjectParameter("DESCRIBEPARAM", dESCRIBEPARAM) :
                new ObjectParameter("DESCRIBEPARAM", typeof(string));
    
            var vALUEPARAMParameter = vALUEPARAM != null ?
                new ObjectParameter("VALUEPARAM", vALUEPARAM) :
                new ObjectParameter("VALUEPARAM", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var nAMEUPDATEParameter = nAMEUPDATE != null ?
                new ObjectParameter("NAMEUPDATE", nAMEUPDATE) :
                new ObjectParameter("NAMEUPDATE", typeof(string));
    
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_PARAMETERS_AGREGA_ACTUALIZA_Result>("UDLAPSIF_PTONOM_PARAMETERS_AGREGA_ACTUALIZA", iDPARAMParameter, dESCRIBEPARAMParameter, vALUEPARAMParameter, eSTATUSParameter, nAMEUPDATEParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_PARAMETERS_OBTENP_Result> UDLAPSIF_PTONOM_PARAMETERS_OBTENP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_PARAMETERS_OBTENP_Result>("UDLAPSIF_PTONOM_PARAMETERS_OBTENP");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_PARAMETER_BUSCARP_Result> UDLAPSIF_PTONOM_PARAMETER_BUSCARP(Nullable<short> iDPARAM)
        {
            var iDPARAMParameter = iDPARAM.HasValue ?
                new ObjectParameter("IDPARAM", iDPARAM) :
                new ObjectParameter("IDPARAM", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_PARAMETER_BUSCARP_Result>("UDLAPSIF_PTONOM_PARAMETER_BUSCARP", iDPARAMParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_PROJECT_AGREGA_ACTUALIZA_Result> UDLAPSIF_PTONOM_PROJECT_AGREGA_ACTUALIZA(Nullable<short> iDPROJECT, string pROJECT, string dESCRIPCION, string nAMEUPDATE, Nullable<bool> eSTATUS, string iDUSER)
        {
            var iDPROJECTParameter = iDPROJECT.HasValue ?
                new ObjectParameter("IDPROJECT", iDPROJECT) :
                new ObjectParameter("IDPROJECT", typeof(short));
    
            var pROJECTParameter = pROJECT != null ?
                new ObjectParameter("PROJECT", pROJECT) :
                new ObjectParameter("PROJECT", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var nAMEUPDATEParameter = nAMEUPDATE != null ?
                new ObjectParameter("NAMEUPDATE", nAMEUPDATE) :
                new ObjectParameter("NAMEUPDATE", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_PROJECT_AGREGA_ACTUALIZA_Result>("UDLAPSIF_PTONOM_PROJECT_AGREGA_ACTUALIZA", iDPROJECTParameter, pROJECTParameter, dESCRIPCIONParameter, nAMEUPDATEParameter, eSTATUSParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_PROJECT_BUSCARPR_Result> UDLAPSIF_PTONOM_PROJECT_BUSCARPR(Nullable<short> iDPROJECT, string pROJECT, string dESCRIPCION, Nullable<bool> eSTATUS)
        {
            var iDPROJECTParameter = iDPROJECT.HasValue ?
                new ObjectParameter("IDPROJECT", iDPROJECT) :
                new ObjectParameter("IDPROJECT", typeof(short));
    
            var pROJECTParameter = pROJECT != null ?
                new ObjectParameter("PROJECT", pROJECT) :
                new ObjectParameter("PROJECT", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_PROJECT_BUSCARPR_Result>("UDLAPSIF_PTONOM_PROJECT_BUSCARPR", iDPROJECTParameter, pROJECTParameter, dESCRIPCIONParameter, eSTATUSParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_PROJECT_OBTENPR_Result> UDLAPSIF_PTONOM_PROJECT_OBTENPR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_PROJECT_OBTENPR_Result>("UDLAPSIF_PTONOM_PROJECT_OBTENPR");
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_CUENTAS_AGREGA_ACTUALIZA_Result> UDLAPSIF_PTONOM_CUENTAS_AGREGA_ACTUALIZA(Nullable<int> iD_CUENTA, string cUENTA, string dESCRIPCION, Nullable<int> iD_CC, Nullable<int> iD_SC, Nullable<int> iD_LA, Nullable<short> iDCURRENCY, Nullable<short> iDTIPOCUENTA, Nullable<short> iDPROJECT, Nullable<bool> cUENTAESPECIAL, Nullable<bool> vALES, Nullable<bool> eSTATUS, string nAMEUPDATE, string iDUSER)
        {
            var iD_CUENTAParameter = iD_CUENTA.HasValue ?
                new ObjectParameter("ID_CUENTA", iD_CUENTA) :
                new ObjectParameter("ID_CUENTA", typeof(int));
    
            var cUENTAParameter = cUENTA != null ?
                new ObjectParameter("CUENTA", cUENTA) :
                new ObjectParameter("CUENTA", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var iD_CCParameter = iD_CC.HasValue ?
                new ObjectParameter("ID_CC", iD_CC) :
                new ObjectParameter("ID_CC", typeof(int));
    
            var iD_SCParameter = iD_SC.HasValue ?
                new ObjectParameter("ID_SC", iD_SC) :
                new ObjectParameter("ID_SC", typeof(int));
    
            var iD_LAParameter = iD_LA.HasValue ?
                new ObjectParameter("ID_LA", iD_LA) :
                new ObjectParameter("ID_LA", typeof(int));
    
            var iDCURRENCYParameter = iDCURRENCY.HasValue ?
                new ObjectParameter("IDCURRENCY", iDCURRENCY) :
                new ObjectParameter("IDCURRENCY", typeof(short));
    
            var iDTIPOCUENTAParameter = iDTIPOCUENTA.HasValue ?
                new ObjectParameter("IDTIPOCUENTA", iDTIPOCUENTA) :
                new ObjectParameter("IDTIPOCUENTA", typeof(short));
    
            var iDPROJECTParameter = iDPROJECT.HasValue ?
                new ObjectParameter("IDPROJECT", iDPROJECT) :
                new ObjectParameter("IDPROJECT", typeof(short));
    
            var cUENTAESPECIALParameter = cUENTAESPECIAL.HasValue ?
                new ObjectParameter("CUENTAESPECIAL", cUENTAESPECIAL) :
                new ObjectParameter("CUENTAESPECIAL", typeof(bool));
    
            var vALESParameter = vALES.HasValue ?
                new ObjectParameter("VALES", vALES) :
                new ObjectParameter("VALES", typeof(bool));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var nAMEUPDATEParameter = nAMEUPDATE != null ?
                new ObjectParameter("NAMEUPDATE", nAMEUPDATE) :
                new ObjectParameter("NAMEUPDATE", typeof(string));
    
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_CUENTAS_AGREGA_ACTUALIZA_Result>("UDLAPSIF_PTONOM_CUENTAS_AGREGA_ACTUALIZA", iD_CUENTAParameter, cUENTAParameter, dESCRIPCIONParameter, iD_CCParameter, iD_SCParameter, iD_LAParameter, iDCURRENCYParameter, iDTIPOCUENTAParameter, iDPROJECTParameter, cUENTAESPECIALParameter, vALESParameter, eSTATUSParameter, nAMEUPDATEParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<UDLAPSIF_PTONOM_CUENTAS_BUSCARC_Result> UDLAPSIF_PTONOM_CUENTAS_BUSCARC(Nullable<int> iD_CUENTA, string cUENTA, string dESCRIPCION, Nullable<bool> eSTATUS, string cC, Nullable<int> iD_SC, Nullable<int> iD_LA)
        {
            var iD_CUENTAParameter = iD_CUENTA.HasValue ?
                new ObjectParameter("ID_CUENTA", iD_CUENTA) :
                new ObjectParameter("ID_CUENTA", typeof(int));
    
            var cUENTAParameter = cUENTA != null ?
                new ObjectParameter("CUENTA", cUENTA) :
                new ObjectParameter("CUENTA", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var eSTATUSParameter = eSTATUS.HasValue ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(bool));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var iD_SCParameter = iD_SC.HasValue ?
                new ObjectParameter("ID_SC", iD_SC) :
                new ObjectParameter("ID_SC", typeof(int));
    
            var iD_LAParameter = iD_LA.HasValue ?
                new ObjectParameter("ID_LA", iD_LA) :
                new ObjectParameter("ID_LA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDLAPSIF_PTONOM_CUENTAS_BUSCARC_Result>("UDLAPSIF_PTONOM_CUENTAS_BUSCARC", iD_CUENTAParameter, cUENTAParameter, dESCRIPCIONParameter, eSTATUSParameter, cCParameter, iD_SCParameter, iD_LAParameter);
        }
    }
}
