//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTONOM_CAT_CUENTAS
    {
        public int ID_CUENTA { get; set; }
        public string CUENTA { get; set; }
        public string DESCRIPCION { get; set; }
        public string NAMEUPDATE { get; set; }
        public bool ESTATUS { get; set; }
        public int ID_CC { get; set; }
        public int ID_LA { get; set; }
        public int ID_SC { get; set; }
        public short IDCURRENCY { get; set; }
        public Nullable<short> IDPROJECT { get; set; }
        public bool VALES { get; set; }
        public short IDTIPOCUENTA { get; set; }
        public string create_user { get; set; }
        public System.DateTime create_time { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_time { get; set; }
        public bool CUENTAESPECIAL { get; set; }
    
        public virtual PTONOM_CAT_COSTCENTER PTONOM_CAT_COSTCENTER { get; set; }
        public virtual PTONOM_CAT_LEDGERACCOUNT PTONOM_CAT_LEDGERACCOUNT { get; set; }
        public virtual PTONOM_CAT_SPENDCATEGORY PTONOM_CAT_SPENDCATEGORY { get; set; }
        public virtual PTONOM_CAT_PROJECT PTONOM_CAT_PROJECT { get; set; }
        public virtual PTONOM_CAT_CURRENCY PTONOM_CAT_CURRENCY { get; set; }
    }
}
