//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTONOM_CAT_CURRENCY
    {
        public PTONOM_CAT_CURRENCY()
        {
            this.PTONOM_CAT_CUENTAS = new HashSet<PTONOM_CAT_CUENTAS>();
        }
    
        public short IDCURRENCY { get; set; }
        public string COUNTRY { get; set; }
        public string CURRENCY { get; set; }
        public string CODE { get; set; }
        public Nullable<short> MINOR_UNIT { get; set; }
        public string SYMBOL { get; set; }
        public bool ESTATUS { get; set; }
    
        public virtual ICollection<PTONOM_CAT_CUENTAS> PTONOM_CAT_CUENTAS { get; set; }
    }
}
