//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTONOM_CAT_LEDGERACCOUNT
    {
        public PTONOM_CAT_LEDGERACCOUNT()
        {
            this.PTONOM_CAT_CUENTAS = new HashSet<PTONOM_CAT_CUENTAS>();
        }
    
        public int ID_LA { get; set; }
        public string LA { get; set; }
        public string DESCRIPCION { get; set; }
        public string NAMEUPDATE { get; set; }
        public bool ESTATUS { get; set; }
        public string create_user { get; set; }
        public System.DateTime create_time { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_time { get; set; }
    
        public virtual ICollection<PTONOM_CAT_CUENTAS> PTONOM_CAT_CUENTAS { get; set; }
    }
}
