//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class xNOMExcelRH
    {
        public string BACHNUMB { get; set; }
        public int ACTINDX { get; set; }
        public string ACTNUMBER { get; set; }
        public decimal CRDTAMT { get; set; }
        public string CURNCYID { get; set; }
        public int CURRNIDX { get; set; }
        public decimal CURYCRDTAMT { get; set; }
        public decimal CURYDEBITAMT { get; set; }
        public decimal DEBITAMT { get; set; }
        public string DSCRIPTN { get; set; }
        public System.DateTime EXCHDATE { get; set; }
        public string REFRENCE { get; set; }
        public string SOURCDOC { get; set; }
        public System.DateTime TRXDATE { get; set; }
        public decimal XCHGRATE { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<bool> isRead { get; set; }
        public int JRNLIDX { get; set; }
        public string CtrlPPTO { get; set; }
    }
}
